### ISSUE TITLE
experiment_root_demo

### ISSUE THREAD

**Issue by MOONBEAR0703** [ergysr/DeepCC#12]
https://github.com/ergysr/DeepCC/blob/dac46711735dccf912c88a88d316e4e860bebe37/get_opts.m#L8
https://github.com/ergysr/DeepCC/blob/dac46711735dccf912c88a88d316e4e860bebe37/get_opts.m#L73
Do the paths above both represent the experiment_root?
Because I have met a error.
`train.py: error: argument --experiment_root: The provided string `experiments/demo_weighted_triplet` is not a valid writeable path.`

**Comment by ergysr** [comment]
The experiment root for appearance models is `src/triplet-reid/experiments` which you need to create manually. It is different from the experiment root of the tracker.

**Comment by MOONBEAR0703** [comment]
[https://github.com/ergysr/DeepCC#pre-computed-features](url)
so I should put the pre-features in `src/triplet-reid/experiments`,right? But what is the difference between `demo` and `demo_weighted_triplet`?

**Comment by ergysr** [comment]
Tracking experiments are stored in experiments/<exp_name_tracking>. There you have all L0-L3 outputs (features, trajectories, visualizations, etc).
Trained appearance models are stored in `src/triplet-reid/experiments/<exp_appearance_model>/`.
So to answer your question, no. The pre-computed features go into the tracking experiments.

**Comment by MOONBEAR0703** [comment]
So I need to create the experiment root for appearance models manually. OK. 
Then for the tracking experiments, does it need to have a fixed path,or I can created it anywhere?

**Comment by MOONBEAR0703** [comment]
When I run embed(opts); I get errors like: `OSError: Using the `data/duke_train.csv` file and `/media/lab324/sdc1/xy/DukeDataset/DukeMTMC/DukeMTMC-reID` as an image root 16522/16522 images are missing`
In the get_opts() you provided, `net.image_root = 'F:/DukeMTMC/DukeMTMC-reID';`.
But when I unzip the `DukeMTMC-reID`, I get two files, `DukeMTMC-reID` and `__MACOSX`.So I change the `net.image_root` to `/media/lab324/sdc1/xy/DukeDataset/DukeMTMC/DukeMTMC-reID`.

**Comment by ergysr** [comment]
For now the paths are relative to `DeepCC/`. Though you can modify the code to make the paths absolute.

Regarding `embed(opts)`, you need to specify the `net.image_root` as you did.  The unzipping of images is supposed to happen when you first run `downloadDukeMTMC`.  Let me know if you are unable to train.

**Comment by MOONBEAR0703** [comment]
OK.I finally make the paths absolute. But when I run `train_duke(opts)` , it has another error:
`Traceback (most recent call last):
  File "train.py", line 586, in <module>
    main()
  File "train.py", line 415, in main
    lambda im, fid, pid: (tf.py_func(augment_images, [im],[tf.float32]), fid, pid))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 851, in map
    return MapDataset(self, map_func)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1839, in __init__
    self._map_func.add_to_graph(ops.get_default_graph())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/function.py", line 484, in add_to_graph
    self._create_definition_if_needed()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/function.py", line 319, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/function.py", line 336, in _create_definition_if_needed_impl
    outputs = self._func(*inputs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1827, in tf_map_func
    ret, [t.get_shape() for t in nest.flatten(ret)])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1827, in <listcomp>
    ret, [t.get_shape() for t in nest.flatten(ret)])
AttributeError: 'list' object has no attribute 'get_shape'`

**Comment by ergysr** [comment]
You are likely using an older version of tensorflow. I am currently using `1.10.0` although the code should work with `1.8.0` as well.

**Comment by MOONBEAR0703** [comment]
@ergysr Yes, what's a sad story! I am using a tensorflow `1.8.0`. But `1.10.0` is released not long ago. You have such a strong executive ability!

**Comment by ergysr** [comment]
@MOONBEAR0703 Try replacing the command in:

https://github.com/ergysr/DeepCC/blob/e9c7fdbb97d68584f52a4c9548265ae0def62610/src/triplet-reid/train_duke.m#L25-L27

with:

`command = [command, ' --flip_augment --flip_augment'];`

This will bypass my own data augmentation (L415) and perform the default flip&crop augmentation. At least this will allow you to train a model.

**Comment by MOONBEAR0703** [comment]
I did. Then it said:` File "train.py", line 396, in main
    lambda fid, pid: common.fid_to_image(fid, pid, image_root=args.image_root,image_size=pre_crop_size if args.crop_augment else net_input_size),  num_parallel_calls=args.loading_threads)   here omits some information.  TypeError: <lambda>() takes 2 positional arguments but 3 were given` So which argument should I omit?

**Comment by ergysr** [comment]
I think in:
https://github.com/ergysr/DeepCC/blob/e9c7fdbb97d68584f52a4c9548265ae0def62610/src/triplet-reid/train.py#L396
it expects:
`lambda im, fid, pid: common.fid_to_image(`

Let me know if this fixes it.

**Comment by MOONBEAR0703** [comment]
Finally, it does work.Thanks a lot~~
